import { describe, expect, it } from 'vitest';
import migrate from './009-ts-node-nodenext.js';
import { Context } from '../../context.js';

const SCAFFOLDED_TSCONFIG = `/*
 * ⚠️⚠️⚠️ THIS FILE WAS SCAFFOLDED BY \`@grafana/create-plugin\`. DO NOT EDIT THIS FILE DIRECTLY. ⚠️⚠️⚠️
 *
 * In order to extend the configuration follow the steps in
 * https://grafana.com/developers/plugin-tools/how-to-guides/extend-configurations#extend-the-typescript-config
 */
{
  "compilerOptions": {
    "alwaysStrict": true,
    "declaration": false,
    "rootDir": "../src",
    "paths": {
      "*": ["../src/*"]
    },
    "typeRoots": ["../node_modules/@types"],
    "resolveJsonModule": true
  },
  "ts-node": {
    "compilerOptions": {
      "module": "commonjs",
      "moduleResolution": "node",
      "target": "es5",
      "esModuleInterop": true
    },
    "transpileOnly": true
  },
  "include": ["../src", "./types"],
  "extends": "@grafana/tsconfig"
}
`;

describe('009-ts-node-nodenext', () => {
  it('should update module, moduleResolution, and target inside ts-node compilerOptions', () => {
    const context = new Context('/virtual');
    context.addFile('.config/tsconfig.json', SCAFFOLDED_TSCONFIG);

    const result = migrate(context);
    const updated = result.getFile('.config/tsconfig.json') || '';

    expect(updated).toContain('"module": "nodenext"');
    expect(updated).toContain('"moduleResolution": "nodenext"');
    expect(updated).toContain('"target": "es2022"');
    expect(updated).not.toContain('"module": "commonjs"');
    expect(updated).not.toContain('"moduleResolution": "node"');
    expect(updated).not.toContain('"target": "es5"');
  });

  it('should preserve the JSONC comment header', () => {
    const context = new Context('/virtual');
    context.addFile('.config/tsconfig.json', SCAFFOLDED_TSCONFIG);

    const result = migrate(context);
    const updated = result.getFile('.config/tsconfig.json') || '';

    expect(updated).toContain('THIS FILE WAS SCAFFOLDED BY');
    expect(updated.startsWith('/*')).toBe(true);
  });

  it('should be idempotent', async () => {
    const context = new Context('/virtual');
    context.addFile('.config/tsconfig.json', SCAFFOLDED_TSCONFIG);

    await expect(migrate).toBeIdempotent(context);
  });

  it('should be a no-op when the file is already migrated', () => {
    const alreadyMigrated = SCAFFOLDED_TSCONFIG.replace('"module": "commonjs"', '"module": "nodenext"')
      .replace('"moduleResolution": "node"', '"moduleResolution": "nodenext"')
      .replace('"target": "es5"', '"target": "es2022"');

    const context = new Context('/virtual');
    context.addFile('.config/tsconfig.json', alreadyMigrated);

    const result = migrate(context);

    expect(result.getFile('.config/tsconfig.json')).toBe(alreadyMigrated);
  });

  it('should be a no-op when .config/tsconfig.json does not exist', () => {
    const context = new Context('/virtual');

    const result = migrate(context);

    expect(result.hasChanges()).toBe(false);
  });

  it('should leave user-customised module/target untouched but always force moduleResolution to nodenext', () => {
    const partiallyCustomised = SCAFFOLDED_TSCONFIG.replace('"target": "es5"', '"target": "es2020"').replace(
      '"moduleResolution": "node"',
      '"moduleResolution": "bundler"'
    );

    const context = new Context('/virtual');
    context.addFile('.config/tsconfig.json', partiallyCustomised);

    const result = migrate(context);
    const updated = result.getFile('.config/tsconfig.json') || '';

    expect(updated).toContain('"module": "nodenext"');
    expect(updated).toContain('"moduleResolution": "nodenext"');
    expect(updated).toContain('"target": "es2020"');
    expect(updated).not.toContain('"moduleResolution": "bundler"');
    expect(updated).not.toContain('"target": "es2022"');
  });
});
