import { describe, expect, it } from 'vitest';
import { parse } from 'jsonc-parser';
import migrate from './009-remove-tsconfig-baseurl.js';
import { Context } from '../../context.js';

const SCAFFOLD_TSCONFIG = `/*
 * ⚠️⚠️⚠️ THIS FILE WAS SCAFFOLDED BY \`@grafana/create-plugin\`. DO NOT EDIT THIS FILE DIRECTLY. ⚠️⚠️⚠️
 */
{
  "compilerOptions": {
    "alwaysStrict": true,
    "rootDir": "../src",
    "baseUrl": "../src",
    "typeRoots": ["../node_modules/@types"],
    "resolveJsonModule": true
  },
  "extends": "@grafana/tsconfig"
}
`;

describe('008-remove-tsconfig-baseurl', () => {
  it('should remove baseUrl and add paths catch-all, preserving comment header and rootDir', () => {
    const context = new Context('/virtual');
    context.addFile('.config/tsconfig.json', SCAFFOLD_TSCONFIG);

    const result = migrate(context);
    const content = result.getFile('.config/tsconfig.json') || '';
    const config = parse(content) as { compilerOptions: Record<string, unknown> };

    expect(config.compilerOptions['baseUrl']).toBeUndefined();
    expect(config.compilerOptions['paths']).toEqual({ '*': ['../src/*'] });
    expect(config.compilerOptions['rootDir']).toBe('../src');
    expect(content).toContain('DO NOT EDIT THIS FILE DIRECTLY');
  });

  it('should be idempotent', async () => {
    const context = new Context('/virtual');
    context.addFile('.config/tsconfig.json', SCAFFOLD_TSCONFIG);

    await expect(migrate).toBeIdempotent(context);
  });

  it('should not modify file when baseUrl is already absent', () => {
    const context = new Context('/virtual');
    const content = `{
  "compilerOptions": {
    "rootDir": "../src",
    "paths": { "*": ["../src/*"] }
  }
}
`;
    context.addFile('.config/tsconfig.json', content);

    const result = migrate(context);

    expect(result.getFile('.config/tsconfig.json')).toBe(content);
  });

  it('should not modify anything when .config/tsconfig.json does not exist', () => {
    const context = new Context('/virtual');

    const result = migrate(context);

    expect(result.hasChanges()).toBe(false);
  });

  it('should merge paths["*"] into an existing paths object without overwriting other entries', () => {
    const context = new Context('/virtual');
    context.addFile(
      '.config/tsconfig.json',
      `{
  "compilerOptions": {
    "rootDir": "../src",
    "baseUrl": "../src",
    "paths": {
      "@components/*": ["../src/components/*"]
    }
  }
}
`
    );

    const result = migrate(context);
    const content = result.getFile('.config/tsconfig.json') || '';
    const config = parse(content) as { compilerOptions: { paths: Record<string, string[]> } };

    expect(config.compilerOptions.paths['@components/*']).toEqual(['../src/components/*']);
    expect(config.compilerOptions.paths['*']).toEqual(['../src/*']);
    expect(config.compilerOptions).not.toHaveProperty('baseUrl');
  });
});
