import { describe, expect, it } from 'vitest';
import migrate from './012-terser-license-file.js';
import { Context } from '../../context.js';

const WEBPACK_CONFIG_PATH = '.config/webpack/webpack.config.ts';
const RSPACK_CONFIG_PATH = '.config/rspack/rspack.config.ts';

const BUNDLER_CONFIG = `/*
 * ⚠️⚠️⚠️ THIS FILE WAS SCAFFOLDED BY \`@grafana/create-plugin\`. DO NOT EDIT THIS FILE DIRECTLY. ⚠️⚠️⚠️
 *
 * In order to extend the configuration follow the steps in
 * https://grafana.com/developers/plugin-tools/how-to-guides/extend-configurations#extend-the-webpack-config
 */

import TerserPlugin from 'terser-webpack-plugin';
import { type Configuration } from 'webpack';

const config = async (env: Record<string, unknown>): Promise<Configuration> => ({
  optimization: {
    minimize: Boolean(env.production),
    minimizer: [
      new TerserPlugin({
        terserOptions: {
          format: {
            comments: (_, { type, value }) => type === 'comment2' && value.trim().startsWith('[create-plugin]'),
          },
          compress: {
            drop_console: ['log', 'info'],
          },
        },
      }),
    ],
  },
});

export default config;
`;

const MIGRATED_BUNDLER_CONFIG = `/*
 * ⚠️⚠️⚠️ THIS FILE WAS SCAFFOLDED BY \`@grafana/create-plugin\`. DO NOT EDIT THIS FILE DIRECTLY. ⚠️⚠️⚠️
 *
 * In order to extend the configuration follow the steps in
 * https://grafana.com/developers/plugin-tools/how-to-guides/extend-configurations#extend-the-webpack-config
 */

import TerserPlugin from 'terser-webpack-plugin';
import { type Configuration } from 'webpack';

const config = async (env: Record<string, unknown>): Promise<Configuration> => ({
  optimization: {
    minimize: Boolean(env.production),
    minimizer: [
      new TerserPlugin({
        extractComments: {
          banner: false,
          filename: 'LICENSE.txt',
        },

        terserOptions: {
          format: {
            comments: (_, { type, value }) => type === 'comment2' && value.trim().startsWith('[create-plugin]'),
          },
          compress: {
            drop_console: ['log', 'info'],
          },
        },
      }),
    ],
  },
});

export default config;
`;

const NO_TERSER_CONFIG = `import { type Configuration } from 'webpack';

const config = async (): Promise<Configuration> => ({
  optimization: {
    minimize: true,
  },
});

export default config;
`;

describe('012-terser-license-file', () => {
  it('should add extractComments before terserOptions in the webpack config', () => {
    const context = new Context('/virtual');
    context.addFile(WEBPACK_CONFIG_PATH, BUNDLER_CONFIG);

    const result = migrate(context);
    const updated = result.getFile(WEBPACK_CONFIG_PATH) ?? '';

    expect(updated).toContain('extractComments');
    expect(updated).toContain('banner: false');
    expect(updated).toContain("filename: 'LICENSE.txt'");
    expect(updated.indexOf('extractComments')).toBeLessThan(updated.indexOf('terserOptions'));
  });

  it('should add extractComments before terserOptions in the rspack config', () => {
    const context = new Context('/virtual');
    context.addFile(RSPACK_CONFIG_PATH, BUNDLER_CONFIG);

    const result = migrate(context);
    const updated = result.getFile(RSPACK_CONFIG_PATH) ?? '';

    expect(updated).toContain('extractComments');
    expect(updated).toContain('banner: false');
    expect(updated).toContain("filename: 'LICENSE.txt'");
    expect(updated.indexOf('extractComments')).toBeLessThan(updated.indexOf('terserOptions'));
  });

  it('should migrate both bundler configs when both exist', () => {
    const context = new Context('/virtual');
    context.addFile(WEBPACK_CONFIG_PATH, BUNDLER_CONFIG);
    context.addFile(RSPACK_CONFIG_PATH, BUNDLER_CONFIG);

    const result = migrate(context);

    expect(result.getFile(WEBPACK_CONFIG_PATH)).toContain('extractComments');
    expect(result.getFile(RSPACK_CONFIG_PATH)).toContain('extractComments');
  });

  it('should print the extractComments block with matching formatting', () => {
    const context = new Context('/virtual');
    context.addFile(WEBPACK_CONFIG_PATH, BUNDLER_CONFIG);

    const result = migrate(context);

    expect(result.getFile(WEBPACK_CONFIG_PATH)).toBe(MIGRATED_BUNDLER_CONFIG);
  });

  it('should be idempotent', async () => {
    const context = new Context('/virtual');
    context.addFile(WEBPACK_CONFIG_PATH, BUNDLER_CONFIG);
    context.addFile(RSPACK_CONFIG_PATH, BUNDLER_CONFIG);

    await expect(migrate).toBeIdempotent(context);
  });

  it('should not modify a config with a pre-existing extractComments setting', () => {
    const customizedConfig = BUNDLER_CONFIG.replace(
      'terserOptions: {',
      'extractComments: false,\n        terserOptions: {'
    );
    const context = new Context('/virtual');
    context.addFile(WEBPACK_CONFIG_PATH, customizedConfig);

    const result = migrate(context);

    expect(result.getFile(WEBPACK_CONFIG_PATH)).toBe(customizedConfig);
  });

  it('should do nothing when no bundler config exists', () => {
    const context = new Context('/virtual');

    const result = migrate(context);

    expect(result.hasChanges()).toBe(false);
  });

  it('should not modify a config without a TerserPlugin', () => {
    const context = new Context('/virtual');
    context.addFile(WEBPACK_CONFIG_PATH, NO_TERSER_CONFIG);

    const result = migrate(context);

    expect(result.getFile(WEBPACK_CONFIG_PATH)).toBe(NO_TERSER_CONFIG);
  });
});
