import { describe, expect, it } from 'vitest';
import migrate from './013-jest-esmodules.js';
import { Context } from '../../context.js';

const JEST_UTILS_PATH = '.config/jest/utils.js';

const JEST_UTILS = `/*
 * ⚠️⚠️⚠️ THIS FILE WAS SCAFFOLDED BY \`@grafana/create-plugin\`. DO NOT EDIT THIS FILE DIRECTLY. ⚠️⚠️⚠️
 *
 * In order to extend the configuration follow the steps in .config/README.md
 */

/*
 * This utility function is useful in combination with jest \`transformIgnorePatterns\` config
 * to transform specific packages (e.g.ES modules) in a projects node_modules folder.
 */
const nodeModulesToTransform = (moduleNames) => \`node_modules\\/(?!.*(\${moduleNames.join('|')})\\/.*)\`;

// Array of known nested grafana package dependencies that only bundle an ESM version
const grafanaESModules = [
  '.pnpm', // Support using pnpm symlinked packages
  '@grafana/schema',
  '@wojtekmaj/date-utils',
  'd3',
  'uuid',
];

module.exports = {
  nodeModulesToTransform,
  grafanaESModules,
};
`;

describe('013-jest-esmodules', () => {
  it('should add @react-hookz/web and @ver0/deep-equal to grafanaESModules', () => {
    const context = new Context('/virtual');
    context.addFile(JEST_UTILS_PATH, JEST_UTILS);

    const result = migrate(context);
    const updated = result.getFile(JEST_UTILS_PATH) ?? '';

    expect(updated).toContain("'@react-hookz/web'");
    expect(updated).toContain("'@ver0/deep-equal'");
    expect(updated.indexOf("'@grafana/schema'")).toBeLessThan(updated.indexOf("'@react-hookz/web'"));
    expect(updated.indexOf("'@ver0/deep-equal'")).toBeLessThan(updated.indexOf("'@wojtekmaj/date-utils'"));
  });

  it('should only add missing modules', () => {
    const context = new Context('/virtual');
    context.addFile(
      JEST_UTILS_PATH,
      JEST_UTILS.replace("'@wojtekmaj/date-utils',", "'@react-hookz/web',\n  '@wojtekmaj/date-utils',")
    );

    const result = migrate(context);
    const updated = result.getFile(JEST_UTILS_PATH) ?? '';

    expect(updated.match(/'@react-hookz\/web'/g)).toHaveLength(1);
    expect(updated.match(/'@ver0\/deep-equal'/g)).toHaveLength(1);
  });

  it('should be idempotent', async () => {
    const context = new Context('/virtual');
    context.addFile(JEST_UTILS_PATH, JEST_UTILS);

    await expect(migrate).toBeIdempotent(context);
  });

  it('should do nothing when the Jest utils file does not exist', () => {
    const context = new Context('/virtual');

    const result = migrate(context);

    expect(result.hasChanges()).toBe(false);
  });

  it('should do nothing when grafanaESModules is missing', () => {
    const context = new Context('/virtual');
    const customizedUtils = JEST_UTILS.replace('const grafanaESModules = [', 'const customESModules = [');
    context.addFile(JEST_UTILS_PATH, customizedUtils);

    const result = migrate(context);

    expect(result.getFile(JEST_UTILS_PATH)).toBe(customizedUtils);
  });

  it('should do nothing when grafanaESModules is not an array', () => {
    const context = new Context('/virtual');
    const customizedUtils = JEST_UTILS.replace(
      /const grafanaESModules = \[[\s\S]*?\];/,
      "const grafanaESModules = require('./grafana-es-modules');"
    );
    context.addFile(JEST_UTILS_PATH, customizedUtils);

    const result = migrate(context);

    expect(result.getFile(JEST_UTILS_PATH)).toBe(customizedUtils);
  });
});
