import { describe, expect, it } from 'vitest';
import migrate from './014-eslint-config-v10.js';
import { Context } from '../../context.js';

const SCAFFOLD_ESLINT_CONFIG = `/*
 * ⚠️⚠️⚠️ THIS FILE WAS SCAFFOLDED BY \`@grafana/create-plugin\`. DO NOT EDIT THIS FILE DIRECTLY. ⚠️⚠️⚠️
 */

import { defineConfig } from 'eslint/config';
import grafanaConfig from '@grafana/eslint-config/flat.js';

export default defineConfig([...grafanaConfig]);
`;

function addPackageJson(context: Context, eslintConfigVersion = '^9.0.0') {
  context.addFile(
    'package.json',
    JSON.stringify({
      devDependencies: {
        '@grafana/eslint-config': eslintConfigVersion,
        '@stylistic/eslint-plugin-ts': '^4.4.0',
        'eslint-plugin-react-hooks': '^7.0.0',
      },
    })
  );
}

describe('014-eslint-config-v10', () => {
  it('should replace the removed flat.js subpath import', () => {
    const context = new Context('/virtual');
    context.addFile('.config/eslint.config.mjs', SCAFFOLD_ESLINT_CONFIG);
    addPackageJson(context);

    const result = migrate(context);
    const content = result.getFile('.config/eslint.config.mjs') || '';

    expect(content).toContain("import grafanaConfig from '@grafana/eslint-config';");
    expect(content).not.toContain('@grafana/eslint-config/flat.js');
    expect(content).toContain('DO NOT EDIT THIS FILE DIRECTLY');
  });

  it('should update package.json dependencies for eslint-config v10', () => {
    const context = new Context('/virtual');
    context.addFile('.config/eslint.config.mjs', SCAFFOLD_ESLINT_CONFIG);
    addPackageJson(context);

    const result = migrate(context);
    const packageJson = JSON.parse(result.getFile('package.json') || '{}');

    expect(packageJson.devDependencies['@grafana/eslint-config']).toBe('^10.0.0');
    expect(packageJson.devDependencies['@stylistic/eslint-plugin']).toBe('^5.10.0');
    expect(packageJson.devDependencies['@stylistic/eslint-plugin-ts']).toBeUndefined();
    expect(packageJson.devDependencies['eslint-plugin-react-hooks']).toBe('^7.1.0');
  });

  it('should not modify anything when package.json does not exist', () => {
    const context = new Context('/virtual');

    const result = migrate(context);

    expect(result.hasChanges()).toBe(false);
  });

  it('should not modify anything when @grafana/eslint-config is already on v10', () => {
    const context = new Context('/virtual');
    context.addFile('.config/eslint.config.mjs', SCAFFOLD_ESLINT_CONFIG.replace('/flat.js', ''));
    addPackageJson(context, '^10.0.0');

    const initialChanges = context.listChanges();
    migrate(context);

    expect(context.listChanges()).toEqual(initialChanges);
  });

  it('should not modify anything when there are no devDependencies', () => {
    const context = new Context('/virtual');
    context.addFile('package.json', JSON.stringify({}));

    const initialChanges = context.listChanges();
    migrate(context);

    expect(context.listChanges()).toEqual(initialChanges);
  });

  it('should be idempotent', async () => {
    const context = new Context('/virtual');
    context.addFile('.config/eslint.config.mjs', SCAFFOLD_ESLINT_CONFIG);
    addPackageJson(context);

    await expect(migrate).toBeIdempotent(context);
  });
});
