import { describe, expect, it } from 'vitest';
import { parse } from 'jsonc-parser';
import migrate from './015-tsconfig-config-dir.js';
import { Context } from '../../context.js';
import { TEMPLATE_PATHS } from '../../../constants.js';
import { renderTemplateFromFile } from '../../../utils/utils.templates.js';
import path from 'node:path';

const SCAFFOLD_TSCONFIG = `/*
 * ⚠️⚠️⚠️ THIS FILE WAS SCAFFOLDED BY \`@grafana/create-plugin\`. DO NOT EDIT THIS FILE DIRECTLY. ⚠️⚠️⚠️
 */
{
  "compilerOptions": {
    "alwaysStrict": true,
    "declaration": false,
    "rootDir": "../src",
    "paths": {
      "*": ["../src/*"]
    },
    "typeRoots": ["../node_modules/@types"],
    "resolveJsonModule": true
  },
  "include": ["../src", "./types"],
  "extends": "@grafana/tsconfig"
}
`;

type TsConfig = {
  compilerOptions: Record<string, unknown>;
  include: string[];
};

function migrateTsConfig(content: string) {
  const context = new Context('/virtual');
  context.addFile('.config/tsconfig.json', content);

  const result = migrate(context);

  return result.getFile('.config/tsconfig.json') || '';
}

describe('015-tsconfig-config-dir', () => {
  it('resolves plugin paths from the extending tsconfig and drops the typeRoots override', () => {
    const content = migrateTsConfig(SCAFFOLD_TSCONFIG);
    const config = parse(content) as TsConfig;

    expect(config.compilerOptions['rootDir']).toBe('${configDir}/src');
    expect(config.compilerOptions['paths']).toEqual({ '*': ['${configDir}/src/*'] });
    expect(config.compilerOptions['typeRoots']).toBeUndefined();
    expect(config.include).toEqual(['${configDir}/src', './types']);
    expect(config.compilerOptions['resolveJsonModule']).toBe(true);
    expect(content).toContain('DO NOT EDIT THIS FILE DIRECTLY');
  });

  it('leaves values that differ from the scaffold untouched', () => {
    const custom = `{
  "compilerOptions": {
    "rootDir": "../app",
    "paths": { "*": ["../app/*"], "@/*": ["../src/*"] },
    "typeRoots": ["../node_modules/@types", "./custom-types"]
  },
  "include": ["../app", "./types"]
}
`;

    expect(migrateTsConfig(custom)).toBe(custom);
  });

  it('matches the tsconfig scaffolded for new plugins', () => {
    const scaffolded = renderTemplateFromFile(path.join(TEMPLATE_PATHS.common, '.config', 'tsconfig.json'), {});

    expect(migrateTsConfig(scaffolded)).toBe(scaffolded);
  });

  it('should be idempotent', async () => {
    const context = new Context('/virtual');
    context.addFile('.config/tsconfig.json', SCAFFOLD_TSCONFIG);

    await expect(migrate).toBeIdempotent(context);
  });

  it('should not modify anything when .config/tsconfig.json does not exist', () => {
    const context = new Context('/virtual');

    const result = migrate(context);

    expect(result.listChanges()).toEqual({});
  });
});
