import { describe, expect, it } from 'vitest';
import migrate from './016-jest-intersection-observer.js';
import { Context } from '../../context.js';

const JEST_SETUP_PATH = '.config/jest-setup.js';

const SCAFFOLD_JEST_SETUP = `/*
 * ⚠️⚠️⚠️ THIS FILE WAS SCAFFOLDED BY \`@grafana/create-plugin\`. DO NOT EDIT THIS FILE DIRECTLY. ⚠️⚠️⚠️
 */

import '@testing-library/jest-dom';
import 'jest-canvas-mock';

Object.defineProperty(global, 'matchMedia', { writable: true, value: () => ({}) });
`;

function setupContext(setup = SCAFFOLD_JEST_SETUP, extraDevDeps: Record<string, string> = {}) {
  const context = new Context('/virtual');
  context.addFile(JEST_SETUP_PATH, setup);
  context.addFile('package.json', JSON.stringify({ devDependencies: { jest: '^29.7.0', ...extraDevDeps } }));
  return context;
}

describe('016-jest-intersection-observer', () => {
  it('should add the intersection-observer import and devDependency, and preserve surrounding content', () => {
    const result = migrate(setupContext());
    const updated = result.getFile(JEST_SETUP_PATH) || '';
    const packageJson = JSON.parse(result.getFile('package.json') || '{}');

    expect(updated).toContain("import 'intersection-observer';");
    expect(updated).toContain('DO NOT EDIT THIS FILE DIRECTLY');
    expect(updated).toContain('matchMedia');
    expect(updated).toContain("import 'jest-canvas-mock';");
    expect(packageJson.devDependencies['intersection-observer']).toBe('^0.12.2');
  });

  it('should not modify anything when the jest-setup file does not exist', () => {
    const context = new Context('/virtual');

    const result = migrate(context);

    expect(result.hasChanges()).toBe(false);
  });

  it('should be idempotent', async () => {
    await expect(migrate).toBeIdempotent(setupContext());
  });
});
