name: Feature request
description: Share an idea to improve our plugin tools or documentation
title: 'Feat: '
labels:
  - enhancement
body:
  - type: markdown
    attributes:
      value: |
        Before opening a feature request, please be sure to check for existing issues. 
        ---
        Thanks for taking the time to share your suggestion
  - type: checkboxes
    id: package
    attributes:
      label: Which areas does this feature request relate to
      description: You may select more than one.
      options:
        - label: 'Create Plugin'
        - label: 'Sign Plugin'
        - label: 'Documentation'
  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: What are you trying to do and what is missing or frustrating?
    validations:
      required: true
  - type: textarea
    id: idea
    attributes:
      label: Solution
      description: Do you have a proposal on how to solve this problem?
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives
      description: Are there any alternatives you've considered?
    validations:
      required: false
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Share any other context or screenshots.
    validations:
      required: false
  - type: checkboxes
    id: contributions
    attributes:
      label: Are you interested in contributing the solution?
      options:
        - label: 'Yes'
        - label: 'No'
