/*
 * ⚠️⚠️⚠️ THIS FILE WAS SCAFFOLDED BY `@grafana/create-plugin`. DO NOT EDIT THIS FILE DIRECTLY. ⚠️⚠️⚠️
 *
 * In order to extend the configuration follow the steps in
 * https://grafana.com/developers/plugin-tools/how-to-guides/extend-configurations#extend-the-eslint-config
 */

import { defineConfig, globalIgnores } from 'eslint/config';
import grafanaConfig from '@grafana/eslint-config';
{{#if isMonorepo}}
import grafanaPluginsPlugin from '@grafana/eslint-plugin-plugins';
{{/if}}

export default defineConfig([
  // Tooling output and caches. Patterns resolve from the plugin's eslint.config.mjs, which imports this file.
  globalIgnores([
    '**/logs',
    '**/*.log',
    '**/npm-debug.log*',
    '**/yarn-debug.log*',
    '**/yarn-error.log*',
    '**/.pnpm-debug.log*',
    '**/node_modules/',
    '.yarn/cache',
    '.yarn/unplugged',
    '.yarn/build-state.yml',
    '.yarn/install-state.gz',
    '**/.pnp.*',
    '**/pids',
    '**/*.pid',
    '**/*.seed',
    '**/*.pid.lock',
    '**/lib-cov',
    '**/coverage',
    '**/dist/',
    '**/artifacts/',
    '**/work/',
    '**/ci/',
    'test-results/',
    'playwright-report/',
    'blob-report/',
    'playwright/.cache/',
    'playwright/.auth/',
    '**/.idea',
    '**/.eslintcache',
  ]),
  ...grafanaConfig,
  {
    rules: {
      'react/prop-types': 'off',
    },
  },
  {
    files: ['src/**/*.{ts,tsx}'],

    languageOptions: {
      parserOptions: {
        project: './tsconfig.json',
      },
    },

    rules: {
      '@typescript-eslint/no-deprecated': 'warn',
    },
  },
  {
    files: ['./tests/**/*'],

    rules: {
      'react-hooks/rules-of-hooks': 'off',
    },
  },
{{#if isMonorepo}}
  {
    // Each plugin is bundled and shipped on its own, so plugins must not import each other's code.
    // Share code through a workspace package in packages/ instead.
    files: ['**/*.{js,jsx,mjs,cjs,ts,tsx}'],
    plugins: { '@grafana/plugins': grafanaPluginsPlugin },
    rules: {
      '@grafana/plugins/no-cross-plugin-imports': 'error',
    },
  },
{{/if}}
]);
