/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation
 
 The sidebars can be generated from the filesystem, or explicitly defined here.
 
 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{ type: 'autogenerated', dirName: '.' }],

  docs: {
    'Getting Started': ['getting-started', 'folder-structure', 'updating-to-new-releases'],
    Development: ['frontend', 'backend'], // TODO: editor-setup, docker
    // 'Building your Plugin': ['production-builds', 'ci'],
    // Testing: ['unit-tests', 'e2e-tests'],
    Distribution: ['distributing-your-plugin', 'signing-your-plugin'],
    'Advanced Usage': ['advanced-configuration', 'nested-plugins'],
  },

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

module.exports = sidebars;
