name: Latest Grafana API compatibility check
on: [pull_request]

jobs:
  compatibilitycheck:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false

{{#if_eq packageManagerName "pnpm"}}
      # pnpm action uses the packageManager field in package.json to
      # understand which version to install.
      - uses: pnpm/action-setup@08c4be7e2e672a47d11bd04269e27e5f3e8529cb # v6.0.0
{{/if_eq}}

      - name: Setup Node.js environment
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: '22'
          cache: '{{ packageManagerName }}'

      - name: Install dependencies
        run: {{ packageManagerInstallCmd }}

      - name: Build plugin
        run: {{ packageManagerName }} run build

      - name: Find module.ts or module.tsx
        id: find-module-ts
        run: |
          MODULETS="$(find ./src -type f \( -name "module.ts" -o -name "module.tsx" \))"
          echo "modulets=${MODULETS}" >> $GITHUB_OUTPUT

      - name: Compatibility check
        uses: grafana/plugin-actions/is-compatible@is-compatible/v1.0.2
        with:
          module: $\{{ steps.find-module-ts.outputs.modulets }}
          comment-pr: "no"
          fail-if-incompatible: "yes"
