/**
 * Algolia DocSearch record for Docusaurus v3
 */
interface DocSearchRecord {
  /**
   * Unique identifier for the record (auto-generated by Algolia)
   */
  objectID: string;

  /**
   * Hierarchical structure of the page content
   */
  hierarchy: {
    lvl0: string | null;
    lvl1: string | null;
    lvl2: string | null;
    lvl3: string | null;
    lvl4: string | null;
    lvl5: string | null;
    lvl6: string | null;
  };

  /**
   * The actual text content of the section
   */
  content: string | null;

  /**
   * Full URL including anchor
   */
  url: string;

  /**
   * URL without the anchor/hash fragment
   */
  url_without_anchor: string;

  /**
   * Anchor link to the specific section (e.g., "#installation")
   */
  anchor: string | null;

  /**
   * Type of record - indicates whether it's content or a heading level
   */
  type: 'content' | 'lvl0' | 'lvl1' | 'lvl2' | 'lvl3' | 'lvl4' | 'lvl5' | 'lvl6';

  /**
   * Language code (for multilingual sites with contextual search)
   */
  lang?: string;

  /**
   * Alternative language field (for compatibility)
   */
  language?: string;

  /**
   * Documentation version (for versioned docs)
   */
  version?: string | string[];

  /**
   * Docusaurus tag for additional categorization
   */
  docusaurus_tag?: string;

  /**
   * Ranking weights used internally by Algolia
   */
  weight?: {
    /**
     * Overall page importance
     */
    pageRank: number;
    /**
     * Heading level importance (higher level = higher weight)
     */
    level: number;
    /**
     * Position on the page (lower = appears earlier)
     */
    position: number;
  };

  /**
   * Optional custom tags for additional filtering/faceting
   */
  tags?: string[];
}
