name: Lapo Docs Embeddings

on:
  push:
    branches:
      - academo/test-lapo

permissions:
  contents: read
  id-token: write

jobs:
  generate-docs-embeddings:
    name: generate-docs-embeddings
    runs-on: ubuntu-latest
    steps:
      - uses: grafana/lapo-docs/github-actions/generate-embeddings@main
        id: generate-embeddings
        with:
          gcs-bucket: lapo-embeddings
          docs-path: docusaurus/docs
          gemini-api-key: ${{ secrets.GEMINI_API_KEY }}

