name: Preview (pkg.pr.new)
on:
  pull_request:
    types: [labeled, synchronize]
permissions:
  contents: read
concurrency:
  group: preview-${{ github.event.pull_request.number }}
  cancel-in-progress: true
jobs:
  preview:
    if: |
      (github.event.action == 'labeled' && github.event.label.name == 'preview') ||
      (github.event.action == 'synchronize' && contains(github.event.pull_request.labels.*.name, 'preview'))
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          # We need to fetch all branches and commits so that Nx affected has a base to compare against.
          fetch-depth: 0
          persist-credentials: false
      - uses: nrwl/nx-set-shas@afb73a62d26e41464e9254689e1fd6122ee683c1 # v5.0.1
      - name: Setup nodejs
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version-file: '.nvmrc'
          package-manager-cache: false

      - name: Install dependencies
        run: npm ci --no-audit
      - name: Build all packages
        run: npm run build
      - name: Publish packages
        run: npm exec pkg-pr-new publish -- './packages/*' --compact --commentWithSha --commentWithDev
