name: Preview (pkg.pr.new)
on:
  pull_request:
    types: [labeled, synchronize]
permissions:
  contents: read
concurrency:
  group: preview-${{ github.event.pull_request.number }}
  cancel-in-progress: true
jobs:
  preview:
    if: |
      (github.event.action == 'labeled' && github.event.label.name == 'preview') ||
      (github.event.action == 'synchronize' && contains(github.event.pull_request.labels.*.name, 'preview'))
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          # We need to fetch all branches and commits so that Nx affected has a base to compare against.
          fetch-depth: 0
          persist-credentials: false
      - uses: nrwl/nx-set-shas@3e9ad7370203c1e93d109be57f3b72eb0eb511b1 # v4.4.0
      - name: Setup nodejs
        uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
        with:
          node-version-file: '.nvmrc'
          package-manager-cache: false

      - name: Install dependencies
        run: npm ci --no-audit
      - name: Build all packages
        run: npm run build
      - name: Publish packages
        run: npm exec pkg-pr-new publish -- './packages/*' --compact --commentWithSha --commentWithDev
