name: Stale Branches

on:
  schedule:
    - cron: '0 11 * * 1-5'

permissions:
  issues: write
  contents: write

jobs:
  stale_branches:
    runs-on: ubuntu-x64
    steps:
    - name: Stale Branches
      uses: crs-k/stale-branches@138918e25f06d439bf76db5305a591d8a3c03678 # v10.0.0
      with:
        #dry-run: false
        pr-check: true
        ignore-issue-interaction: true
