name: Test docs build

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  changes:
    runs-on: ubuntu-x64
    permissions:
      pull-requests: read
    outputs:
      docs: ${{ steps.filter.outputs.docs }}
    steps:
      - uses: dorny/paths-filter@fbd0ab8f3e69293af611ebaee6363fc25e6d187d # v4.0.1
        id: filter
        with:
          filters: |
            docs:
              - '.github/workflows/deploy-to-developer-portal-dev.yml'
              - '.github/workflows/deploy-to-developer-portal-prod.yml'
              - '.github/workflows/test-build.yml'
              - 'docusaurus/**'
              - 'package-lock.json'

  build-docs:
    needs: changes
    if: ${{ needs.changes.outputs.docs == 'true' }}
    runs-on: ubuntu-x64
    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Setup nodejs
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version-file: '.nvmrc'
          registry-url: 'https://registry.npmjs.org'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci
      - name: Build documentation website (Dev Portal)
        run: npm run build -w website
