name: Run commands when issues or PRs are labeled
on:
  issues:
    types: [ labeled ]
  pull_request:
    types: [ labeled ]
jobs:
  main:
    if: ${{ (github.event.pull_request == false || github.event.pull_request.head.repo.full_name == github.repository) && github.actor != 'dependabot[bot]' }}    
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Actions
        uses: actions/checkout@v4
        with:
          repository: grafana/grafana-github-actions
          path: ./actions
          ref: main
      - name: Install Actions
        run: npm install --production --prefix ./actions
      - name: Run Commands
        uses: ./actions/commands
        with:
          token: ${{ secrets.ISSUE_COMMANDS_TOKEN }}
          configPath: issue_commands
